exactly/app

components/markets/MarketsTables/index.tsx
components/markets/MarketsTables/poolTable/index.tsx

🩹 decouple graph call

---

components/markets/MarketsTables/index.tsx
contexts/GlobalErrorContext.tsx
hooks/useDashboard.ts
hooks/useFixedPoolTransactions.ts
hooks/useFloatingPoolAPR.ts
hooks/useHistoricalRates.ts
i18n/es/translation.json
pages/_app.tsx

✨ Show global warning if The Graph is having issues

---

components/asset/MaturityPool/MaturityPoolInfo/index.tsx
hooks/useFloatingPoolAPR.ts
i18n/es/translation.json

Hotfix some zero division exception

🚑️ hotfix asset page

---

components/Topbar/index.tsx
i18n/es/translation.json
pages/_app.tsx
styles/theme.ts

Added topbar to notify users about the OP upgrade.
closes #1060

✨ OP Bedrock upgrade notification

---

components/DebtManager/Operation/index.tsx
components/DebtManager/Overview/index.tsx
components/DebtManager/PositionTable/index.tsx
components/dashboard/DashboardContent/FloatingPoolDashboard/FloatingPoolDashboardTable/TableRowFloatingPool/index.tsx
components/markets/MarketsBasic/Options/index.tsx
i18n/es/translation.json
package-lock.json
package.json

There is no ticket for this.
- Use correct protocol version
- Updates to translations
- Add details for fixed borrows in rollover modal

✨ Debt Manager: Fixes

---

components/charts/ButtonsChart/index.tsx
components/dashboard/DashboardContent/DashboardMobile/index.tsx
components/dashboard/DashboardContent/FixedPoolDashboard/FixedPoolDashboardTable/TableRowFixedPool/index.tsx
components/dashboard/DashboardContent/FloatingPoolDashboard/FloatingPoolDashboardTable/TableRowFloatingPool/index.tsx
styles/theme.ts

💄 Fix dark mode & border color of button group

---

components/Velodrome/index.tsx
hooks/useEXA.ts
hooks/useEXAGauge.ts
hooks/useEXAPool.ts
hooks/usePreviewerExactly.ts
hooks/useSocketAPI.ts
i18n/es/translation.json
package-lock.json
package.json
types/Bridge.tsx
utils/socket.ts
wagmi.config.ts

✨ velo: add APR

---

.github/workflows/preview.yaml
components/APRWithBreakdown/index.tsx
components/Navbar/index.tsx
components/OperationsModal/ModalInput/index.tsx
components/SocketAssetSelector/index.tsx
components/StakingModal/index.tsx
components/Velodrome/index.tsx
components/common/modal/ModalAlert/index.tsx
hooks/useEXA.ts
hooks/useEXAGauge.ts
hooks/useEXAPool.ts
hooks/useProtoStaker.ts
hooks/useSocketAPI.ts
hooks/useSocketAssets.ts
hooks/useVelo.ts
i18n/es/translation.json
package-lock.json
package.json
types/Bridge.tsx
utils/socket.ts
wagmi.config.ts

✨ Provide EXA liquidity on Velodrome

---

components/OperationsModal/AvailableAmount/index.tsx
tests/e2e/specs/3-floating-borrow-repay/usdc.ts
tests/e2e/specs/3-floating-borrow-repay/weth.ts
tests/e2e/steps/actions.ts
tests/e2e/steps/common/borrow.ts
tests/e2e/steps/common/deposit.ts
tests/e2e/steps/common/repay.ts
tests/e2e/steps/common/withdraw.ts
tests/e2e/steps/modal.ts
tests/e2e/steps/simple.ts
tests/e2e/utils/tenderly.ts

This fixes the e2e tests
Thoughts about changing the framework or ideas on how to speed CI? It took 42 mins this run.

🩹 e2e: fix tests

---

components/StakingModal/index.tsx

Closes #1168
See https://github.com/exactly/app/issues/1168#issuecomment-1668432388

🩹 stake: add minimum supply

---

components/Navbar/index.tsx
components/Velodrome/StakingModal/index.tsx
components/Velodrome/index.tsx
hooks/useVELO.ts

PR 1/x
This should reduce considerably the current amount of RPC calls

🩹 stake: reduce rpc calls

---

components/operations/Repay/index.tsx
components/operations/RepayAtMaturity/index.tsx
components/operations/Withdraw/index.tsx
components/operations/WithdrawAtMaturity/index.tsx
hooks/useApprove.ts
hooks/useBorrow.ts
hooks/useBorrowAtMaturity.ts
hooks/useDeposit.ts
hooks/useDepositAtMaturity.ts

♻️ approve: refactor approval flow

---

.github/workflows/preview.yaml

🐛 E2E: Publish on merge to main

---

components/DebtManager/Operation/index.tsx

Fixes issue with some signatures being invalid at submit

🐛 Rollover: use same value

---

package-lock.json
package.json

Next.js 13.5 improves local dev performance and reliability with:
22% faster local server startup: Iterate faster with the App & Pages Router
29% faster HMR (Fast Refresh): For faster iterations when saving changes
Optimized Package Imports: Faster updates when using popular icon and component libraries
next/image Improvements: <picture>, art direction, and dark mode support
And over 438 bugs patched!

⬆️ upgrade next to 13.5

---

pages/api/circulating-supply.ts

got `132277978350310331891917` as result (~132K)

✨ circulating supply endpoint

---

next.config.mjs

This just adds a missing security header to nextjs config

🔒️ Config: add headers

---

components/SwitchTheme/index.tsx
e2e/components/modal.ts
e2e/specs/3-fixed-deposit-withdraw/weth.spec.ts
hooks/useMerkleTree.ts
hooks/useWeb3.ts
package-lock.json
package.json
pages/_app.tsx
pages/activity.tsx
utils/client.ts

This
- Introduces Web3Modal V3
- Removes packages related to V2
- Upgrades viem & wagmi
Tests:
- Tested using an injected wallet
- Tested using Wallet Connect
- Tested using Safe

✨ Web3Modal V3

---

components/RiskFeed/Decode/index.tsx
components/RiskFeed/Events/index.tsx
components/RiskFeed/Feed/index.tsx
components/RiskFeed/api/index.tsx
queries/getTimelockControllerCalls.ts

closes #1261 
- Increase events/tx count
- Group executions with schedules.
- Group events and list them if there is no safe TX that contains them

♻️ activity: group schedule & execution

---

middleware.ts

This disables the geofence for api calls
- Current: https://cors.jg.ar/https://app.exact.ly/api/circulating-exa
- Preview: https://cors.jg.ar/https://app-rl8khvhlg.exactly.app/api/circulating-exa

🩹 middleware: disable geofence for api calls

---

components/APRWithBreakdown/index.tsx
components/asset/FloatingPool/FloatingPoolInfo/index.tsx
components/asset/MaturityPool/MaturityPoolInfo/index.tsx
config/numbers.json
hooks/useRewards.ts

Filters rates instead of rewards from the user

🩹 rewards: filter rates

---

components/Credit/index.tsx
e2e/specs/8-vesting/esEXA.spec.ts

👽 debit2credit: change lemon deposit config

---

components/ActiveStream/index.tsx
components/SelectMarketsView/index.tsx
hooks/useEscrowedEXA.ts
i18n/es/translation.json
pages/vesting.tsx

✨vesting: streams consolidation panel

---

components/ActiveStream/index.tsx
pages/vesting.tsx

🚸 add usd price to vesting panel

---

components/VestingInput/index.tsx
e2e/specs/8-vesting/esEXA.spec.ts

🚸 vesting: show remaining amount of EXA required

---

pages/index.tsx
pages/t&c.tsx

base is branch `gh-pages` (exa app landing page)
t&c source: https://docs.google.com/document/d/1hKMUKA4R_sdrqAHJZy6tGhF9k-exTZnlzVqmCqn3Ljs/edit

💬 add copyright information and terms and conditions link

---

components/NewIRMBanner/index.tsx
i18n/es/translation.json
pages/_app.tsx

🚸 add notice for new IRM update

---

pages/index.tsx

https://twitter.com/jessepollak/status/1764742947218858477

💬 replace "self-custodial" with "onchain" on exa app landing page

---

components/asset/FloatingPool/FloatingPoolInfo/index.tsx

♻️ borrow-apr: use borrow apr from account-data

---

components/Credit/Borrow.tsx
components/Credit/index.tsx

closes https://github.com/exactly/app/issues/1380

🩹 debit2credit: use bridged USDC by default

---

components/RewardsModal/index.tsx
components/asset/MaturityPool/MaturityPoolsTable/index.tsx
i18n/es/translation.json

🚸 move totals to tooltip in MaturityPool & uncheck 0 amounts in RewardsModal

---

components/ExtraFinance/index.tsx
components/Navbar/index.tsx
i18n/es/translation.json
pages/strategies.tsx

✨ add Extra Finance deposit button

---

components/staking/StakedEXASummary/index.tsx
utils/calculateStakingAPR.ts

🐛 staking: fix decimals for staking APR
